import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    welcome: 'Welcome to Jordan Medical Tourism',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    phone: 'Phone Number',
    selectRole: 'Select Your Role',
    patient: 'Patient',
    companion: 'Companion',
    serviceProvider: 'Service Provider',
    medicalBooking: 'Medical Booking',
    recoveryStay: 'Recovery Stay',
    tourism: 'Tourism & Tours',
    transport: 'Transport',
    supportServices: 'Support Services',
    selectSpecialty: 'Select Medical Specialty',
    findHospitals: 'Find Hospitals',
    bookAppointment: 'Book Appointment',
    viewProfile: 'View Hospital Profile',
    rating: 'Rating',
    reviews: 'Reviews',
    location: 'Location',
    pricing: 'Pricing',
    consultation: 'Consultation',
    bookNow: 'Book Now',
    profile: 'Profile',
    bookings: 'My Bookings',
    logout: 'Logout',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    back: 'Back',
    next: 'Next',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    cardiology: 'Cardiology',
    orthopedics: 'Orthopedics',
    ophthalmology: 'Ophthalmology',
    neurology: 'Neurology',
    oncology: 'Oncology',
    dermatology: 'Dermatology',
    pediatrics: 'Pediatrics',
    psychiatry: 'Psychiatry',
    yearsExperience: 'Years of Experience',
    availableLanguages: 'Available Languages',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    bookingConfirmed: 'Booking Confirmed!',
    paymentSuccessful: 'Payment Successful',
    dashboard: 'Dashboard',
    discoverJordan: 'Discover Jordan\'s Medical Excellence',
    qualityCare: 'World-class healthcare with warm hospitality',
  },
  ar: {
    welcome: 'مرحباً بكم في السياحة العلاجية في الأردن',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    selectRole: 'اختر دورك',
    patient: 'مريض',
    companion: 'مرافق',
    serviceProvider: 'مزود خدمة',
    medicalBooking: 'الحجز الطبي',
    recoveryStay: 'إقامة النقاهة',
    tourism: 'السياحة والجولات',
    transport: 'النقل',
    supportServices: 'الخدمات المساندة',
    selectSpecialty: 'اختر التخصص الطبي',
    findHospitals: 'البحث عن المستشفيات',
    bookAppointment: 'حجز موعد',
    viewProfile: 'عرض ملف المستشفى',
    rating: 'التقييم',
    reviews: 'المراجعات',
    location: 'الموقع',
    pricing: 'الأسعار',
    consultation: 'استشارة',
    bookNow: 'احجز الآن',
    profile: 'الملف الشخصي',
    bookings: 'حجوزاتي',
    logout: 'تسجيل الخروج',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    save: 'حفظ',
    back: 'رجوع',
    next: 'التالي',
    search: 'بحث',
    filter: 'تصفية',
    sort: 'ترتيب',
    cardiology: 'أمراض القلب',
    orthopedics: 'العظام',
    ophthalmology: 'طب العيون',
    neurology: 'طب الأعصاب',
    oncology: 'طب الأورام',
    dermatology: 'الأمراض الجلدية',
    pediatrics: 'طب الأطفال',
    psychiatry: 'الطب النفسي',
    yearsExperience: 'سنوات الخبرة',
    availableLanguages: 'اللغات المتاحة',
    selectDate: 'اختر التاريخ',
    selectTime: 'اختر الوقت',
    bookingConfirmed: 'تم تأكيد الحجز!',
    paymentSuccessful: 'تم الدفع بنجاح',
    dashboard: 'لوحة التحكم',
    discoverJordan: 'اكتشف التميز الطبي في الأردن',
    qualityCare: 'رعاية صحية عالمية المستوى مع ضيافة دافئة',
  },
  fr: {
    welcome: 'Bienvenue au Tourisme Médical en Jordanie',
    signIn: 'Se connecter',
    signUp: 'S\'inscrire',
    email: 'Email',
    password: 'Mot de passe',
    name: 'Nom complet',
    phone: 'Numéro de téléphone',
    selectRole: 'Sélectionnez votre rôle',
    patient: 'Patient',
    companion: 'Accompagnateur',
    serviceProvider: 'Prestataire de services',
    medicalBooking: 'Réservation Médicale',
    recoveryStay: 'Séjour de Récupération',
    tourism: 'Tourisme et Excursions',
    transport: 'Transport',
    supportServices: 'Services de Soutien',
    selectSpecialty: 'Sélectionner la Spécialité Médicale',
    findHospitals: 'Trouver des Hôpitaux',
    bookAppointment: 'Prendre Rendez-vous',
    viewProfile: 'Voir le Profil de l\'Hôpital',
    rating: 'Évaluation',
    reviews: 'Avis',
    location: 'Emplacement',
    pricing: 'Tarification',
    consultation: 'Consultation',
    bookNow: 'Réserver Maintenant',
    profile: 'Profil',
    bookings: 'Mes Réservations',
    logout: 'Déconnexion',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    save: 'Enregistrer',
    back: 'Retour',
    next: 'Suivant',
    search: 'Rechercher',
    filter: 'Filtrer',
    sort: 'Trier',
    cardiology: 'Cardiologie',
    orthopedics: 'Orthopédie',
    ophthalmology: 'Ophtalmologie',
    neurology: 'Neurologie',
    oncology: 'Oncologie',
    dermatology: 'Dermatologie',
    pediatrics: 'Pédiatrie',
    psychiatry: 'Psychiatrie',
    yearsExperience: 'Années d\'Expérience',
    availableLanguages: 'Langues Disponibles',
    selectDate: 'Sélectionner la Date',
    selectTime: 'Sélectionner l\'Heure',
    bookingConfirmed: 'Réservation Confirmée!',
    paymentSuccessful: 'Paiement Réussi',
    dashboard: 'Tableau de Bord',
    discoverJordan: 'Découvrez l\'Excellence Médicale de la Jordanie',
    qualityCare: 'Des soins de classe mondiale avec une hospitalité chaleureuse',
  },
  tr: {
    welcome: 'Ürdün Medikal Turizmine Hoş Geldiniz',
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    name: 'Ad Soyad',
    phone: 'Telefon Numarası',
    selectRole: 'Rolünüzü Seçin',
    patient: 'Hasta',
    companion: 'Refakatçi',
    serviceProvider: 'Hizmet Sağlayıcı',
    medicalBooking: 'Medikal Rezervasyon',
    recoveryStay: 'İyileşme Konaklama',
    tourism: 'Turizm ve Turlar',
    transport: 'Ulaşım',
    supportServices: 'Destek Hizmetleri',
    selectSpecialty: 'Medikal Uzmanlık Seçin',
    findHospitals: 'Hastane Bul',
    bookAppointment: 'Randevu Al',
    viewProfile: 'Hastane Profilini Görüntüle',
    rating: 'Değerlendirme',
    reviews: 'İncelemeler',
    location: 'Konum',
    pricing: 'Fiyatlandırma',
    consultation: 'Konsültasyon',
    bookNow: 'Şimdi Rezerve Et',
    profile: 'Profil',
    bookings: 'Rezervasyonlarım',
    logout: 'Çıkış Yap',
    cancel: 'İptal',
    confirm: 'Onayla',
    save: 'Kaydet',
    back: 'Geri',
    next: 'İleri',
    search: 'Ara',
    filter: 'Filtrele',
    sort: 'Sırala',
    cardiology: 'Kardiyoloji',
    orthopedics: 'Ortopedi',
    ophthalmology: 'Göz Hastalıkları',
    neurology: 'Nöroloji',
    oncology: 'Onkoloji',
    dermatology: 'Dermatoloji',
    pediatrics: 'Pediatri',
    psychiatry: 'Psikiyatri',
    yearsExperience: 'Yıl Deneyim',
    availableLanguages: 'Mevcut Diller',
    selectDate: 'Tarih Seç',
    selectTime: 'Saat Seç',
    bookingConfirmed: 'Rezervasyon Onaylandı!',
    paymentSuccessful: 'Ödeme Başarılı',
    dashboard: 'Gösterge Paneli',
    discoverJordan: 'Ürdün\'ün Medikal Mükemmelliğini Keşfedin',
    qualityCare: 'Sıcak misafirperverlikle dünya standartlarında sağlık hizmeti',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};